### ISSUE TITLE
Does not work with German umlauts

### ISSUE THREAD

**Issue by mascoda** [wcg104/keywordextractor#1]
Hi @wcg104,
You have done a great job. 
Unfortunately, extracting keywords does not work with German umlauts.
 
**Example**
Input: Hemdärmel
Expected: Hemdärmel
Received: Hemd, rmel

![grafik](https://github.com/wcg104/keywordextractor/assets/34571629/e7fb1c47-a1b9-4028-a035-805e3999dff5)

**Comment by wcg104** [comment]
I found the solution but we need to test all the case after that will upload the new version
